spring:
  application:
    name: auth-server
  config:
    import: configserver:http://localhost:8888
  #import: optional:configserver:http://localhost:8888
isepat:
  adresse: Diamniadio
management:
  endpoints:
    health:
    web:
      exposure:
        include:
          - health
          - refresh
          - metrics
          - env
          - configprops
  endpoint:
    configprops:
      show-values: always